name: Java Selenium Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java code
      run: |
        mkdir -p bin
        javac -cp "lib/*" -d bin src/*.java

    - name: Run TestNG tests
      run: |
        java -cp "lib/*:bin" org.testng.TestNG testng.xml
