name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Create bin directory
      run: mkdir -p bin

    - name: Compile Java files
      run: |
        javac -d bin -cp "lib/*" $(find src -name "*.java")

    - name: Run TestNG tests
      run: |
        java -cp "bin:lib/*" org.testng.TestNG testng.xml
