name: Run Selenium Tests Without Maven

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Selenium and WebDriver JARs
        run: |
          mkdir libs
          wget -P libs https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/4.17.0/selenium-java-4.17.0.jar
          wget -P libs https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-api/4.17.0/selenium-api-4.17.0.jar
          wget -P libs https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-chrome-driver/4.17.0/selenium-chrome-driver-4.17.0.jar
          wget -P libs https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-support/4.17.0/selenium-support-4.17.0.jar
          wget -P libs https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-http/4.17.0/selenium-http-4.17.0.jar
          wget -P libs https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-devtools-v120/4.17.0/selenium-devtools-v120-4.17.0.jar

      - name: Compile Java files
        run: javac -cp "libs/*" src/**/*.java

      - name: Run Tests
        run: java -cp "libs/*:src" your.package.MainClassName
